name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x64

      - name: Build application
        run: |
          mingw32-make

      - name: Package application
        run: |
          mkdir -p release
          cp ipc.exe release/
          cp README.md release/
          cp LICENSE release/ || echo "No LICENSE file found"

      - name: Create ZIP archive
        run: |
          Compress-Archive -Path release/* -DestinationPath ipc-${{ github.ref_name }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: IPC ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ipc-${{ github.ref_name }}.zip
            ipc.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}